mySQL =/= SQlite
I redid most of it so the network capabilities should work temporariy,
before I put some good coding practices in it. But I have 3 errors in my
FoodTable XML file. Two of them are Error:(34) No resource identifier
found for attribute 'layout_alightParentLeft or layout_alignParentTop'
in package 'android'. The other one is Error:Execution failed for task
':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute
aapt.